#!/bin/bash

set -ex

pelias compose kill
sudo rm -rf /home/julian/data/pelias/docker/portland_metro/*

pelias compose pull
pelias elastic start
pelias elastic wait
pelias elastic create
pelias download all
pelias prepare all
pelias import all
pelias compose up

sleep 30

# optionally run tests
pelias test run
